---
title: "Confirmatory Factor Analysis"
author: "Statsomat.com"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    toc_depth: 2
fontsize: 9pt
classoption: landscape
params:
  data: NA
  filename: NA
  fencoding: NA
  decimal: NA
  enc_guessed: NA
  vars1: NA
header-includes:
   - \usepackage{xcolor}
   - \setmainfont[BoldFont=FiraSans-Bold, Extension=.otf]{FiraSans-Regular}
   - \usepackage{booktabs}
   - \usepackage{longtable}
   - \usepackage{float}
---


```{r child = 'report_kernel.Rmd'}
```


```{r include=FALSE}
if (exists("eval")) eval_code <- eval else eval_code <- FALSE
```

 
```{r, results="asis", eval=eval, echo=FALSE}
cat("\n# R Packages", fill=TRUE)
cat("To run the R code you need to install following packages. The version number may play in some cases a role.", fill=TRUE)
cat("\\newline ")
cat("\\newline ")
cat("R version:", paste0(R.Version()[c("major","minor")], collapse = "."), fill=TRUE)
cat("\\newline ")
cat("Package data.table, version:", paste0(packageVersion("data.table")), fill=TRUE)
cat("\\newline ")
cat("Package knitr, version:", paste0(packageVersion("knitr")), fill=TRUE)
cat("\\newline ")
cat("Package psych, version:", paste0(packageVersion("psych")), fill=TRUE)
cat("\\newline ")
cat("Package Hmisc, version:", paste0(packageVersion("Hmisc")), fill=TRUE)
cat("\\newline ")
cat("Package reshape2, version:", paste0(packageVersion("reshape2")), fill=TRUE)
cat("\\newline ")
cat("Package ggplot2, version:", paste0(packageVersion("ggplot2")), fill=TRUE)
cat("\\newline ")
cat("Package gridExtra, version:", paste0(packageVersion("gridExtra")), fill=TRUE)
cat("\\newline ")
cat("Package car, version:", paste0(packageVersion("car")), fill=TRUE)
cat("\\newline ")
cat("Package PerformanceAnalytics, version:", paste0(packageVersion("PerformanceAnalytics")), fill=TRUE)
cat("\\pagebreak")
```


\pagestyle{empty} 


```{r, results="asis", eval=eval_code, echo=FALSE}
cat("\n# R Code ", fill=TRUE)
cat("\\normalsize\\textcolor{blue}{Instructions\\newline
If not already available, please install R, RStudio and the requiered packages listed on the previous page. We assume that your data is stored at this location: \"C:\\textbackslash \". If not, please change the path to your data in the code below. For Windows users, avoid to use paths containing white spaces. Copy the code below, paste it carefully in a new R Script within RStudio and run it. The numerical results will be printed in the Console. The graphs can be accessed in the Plots tab. }
\\newline")
```

<style>
pre.whites {
    background-color: #ffffff !important;
}
</style>

```{whites, eval=FALSE, echo = eval_code}
# Import required libraries
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(PerformanceAnalytics))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(car))
```


```{r, results="asis", eval=eval_code, echo=FALSE}
cat("\\# `Define the path to your data (please remark the forward slash)`")
cat("\\newline ")  
cat("`filepath <-")
cat(paste0("\"C:/",params$filename[1],"\"`"))
```


```{r, results="asis", eval=eval_code, echo=FALSE}
if (params$decimal == "auto"){
  cat("\\# `Upload the data`")
  cat("\\newline ")  
 datainput1 <- fread(params$filename$datapath, header = "auto", sep="auto", dec=".", encoding = "UTF-8", data.table = FALSE, na.strings = "")
  
   # Probably comma as decimal
  colnames <- sapply(datainput1, function(col) is.numeric(col) & Negate(is.integer)(col))
  if (sum(colnames) == 0L){
    cat(paste0("`df <- fread(filepath, header =\"auto\", sep =\"auto\", dec =\",\", encoding =\"UTF-8\", data.table = FALSE, na.strings = \"\")`"))
    
  } else {
    cat(paste0("`df <- fread(filepath, header =\"auto\", sep =\"auto\", dec =\".\", encoding =\"UTF-8\", data.table = FALSE, na.strings = \"\")`"))
  }
  
} else {
  cat("\\# `Upload the data`")
  cat("\\newline ")
  cat(paste0("`df <- fread(filepath, header = \"auto\", sep =\"auto\", dec = \"", params$decimal,"\", encoding =  \"UTF-8\", data.table = FALSE, na.strings = \"\")`"))
  
}
```

```{r child = 'report_code_common.Rmd', eval=eval_code}
```
